splash = false
preload = /home/zerom/Pictures/wallpaper/wallhaven-mlzoy1_1920x1080.png
wallpaper {
    monitor = eDP-1
    path = /home/zerom/Pictures/wallpaper/wallhaven-mlzoy1_1920x1080.png
    fit_mode = cover
}
